version: '3.8'

services:
  db:
    image: postgres:16.0
    volumes:
      - ./academic_journal/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
  backend:
    build: 
      dockerfile: ./academic_journal/Dockerfile
    command: sh ./run_backend.sh
    volumes:
      - ./academic_journal:/usr/src/academic_journal/
    ports:
      - 10000:8000
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
    depends_on:
      - db
    env_file:
      - ./.env
