# Generated by Django 5.1.3 on 2024-12-10 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='ranks',
        ),
        migrations.AddField(
            model_name='rank',
            name='lesson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_rank', to='api.lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order_in_day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rank',
            name='rank',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='semester',
            name='end_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start_year',
            field=models.IntegerField(),
        ),
    ]
